# Generated by Django 2.2.3 on 2019-07-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publishing_date', 'id']},
        ),
    ]
